//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De_Gaverbeek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPosts
    {
        public int PostID { get; set; }
        public Nullable<System.DateTime> PostDatum { get; set; }
        public byte[] PostImage { get; set; }
    }
}
